### ISSUE TITLE
maxpc with utf-8 on lispworks

### ISSUE THREAD

**Issue by jibanes** [eugeneia/maxpc#10]
In the following, please note that "⍳" is the greek character "iota".
```
SBCL:
* (parse '(a⍳c) (%some (=element)))

(A⍳C)
T
T

Lispworks 7.1:
MY-PACKAGE 14 > (parse '(a⍳c) (%some (=element)))

Error: Cannot read character U+008D as part of a token because it has constituent trait 'invalid'.
  1 (abort) Return to level 0.
  2 Return to top-level loop.
  3 Return from multiprocessing.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

MY-PACKAGE 14 : 1 > :b
Call to ERROR
Call to READ
Call to (METHOD STREAM::STREAM-READ-WRAPPER (T T))
Call to (METHOD STREAM::STREAM-READ-WRAPPER (SYSTEM::LINE-BUFFER-STREAM T))
Call to READ-PRESERVING-WHITESPACE
Call to MP::DEFAULT-LISTENER-FUNCTION
Call to MP::PROCESS-SG-FUNCTION

MY-PACKAGE 15 : 1 > 
;; End-of-file in a listener, exiting one level.

MY-PACKAGE 15 > (parse '(abc) (%some (=element)))
(ABC)
T
T

MY-PACKAGE 16 > (flexi-streams:string-to-octets "a⍳c")
#(97 226 141 179 99)

MY-PACKAGE 17 > (describe "a⍳c")

"a⍳c" is a SIMPLE-TEXT-STRING
0      #\a
1      #\�
2      #\U+008D
3      #\�
4      #\c

```

**Comment by eugeneia** [comment]
MaxPC should be 100% portable Common Lisp, but I would not immediately conclude that this is a Lispworks bug. I don’t have a Lispworks installation with which to investigate this further though (the personal eidition won’t start on my box because of some obscure GTK error). Given temporary SSH access to a box with Lispworks I might offer to investigate this further.

**Comment by eugeneia** [comment]
It seems as LispWorks does not support that particular Unicode character in symbol names? In the session below I am trying out a few things:

* I can reproduce the error you reported without loading/invoking MaxPC, i.e. it happens when LispWorks tries to read/intern(?) the symbol `a⍳c`
* LispWorks seems to capable of unicode in general, i.e. I can intern the symbol `λ`
* …and `(parse '(aλc) (%some (=element)))` seems to work fine
* LispWorks has a possibly conforming but IMHO bad implementation of Unicode strings, i.e. the string "λ" has length 2, as can be seen when trying `(parse "aλc" (%some (=element)))`, it looks even weirder when parsing `"a⍳c"` which LispWorks somehow represents as a string of five characters

I am tempted to conclude that these are not bugs in MaxPC (well, the error when reading `'a⍳c` certainly isn’t), but I might be wrong about the behavior related to strings. I don’t know of any standard CL functions that would let me implement this in a way that would work in LispWorks though.

```
[max@ip-192-168-33-245 ~]$ lw-console --no-init
; Loading text file /usr/lib64/LispWorks/lib/7-1-0-0/private-patches/load.lisp
LispWorks(R): The Common Lisp Programming Environment
Copyright (C) 1987-2017 LispWorks Ltd.  All rights reserved.
Version 7.1.0
Saved by root as lw-console, at 18 Jan 2018 13:26
User max on ip-192-168-33-245
; Loading text file /usr/lib64/LispWorks/lib/7-1-0-0/config/siteinit.lisp
;  Loading text file /usr/lib64/LispWorks/lib/7-1-0-0/private-patches/load.lisp
; Loading text file /home/max/.lispworks
;  Loading text file /home/max/quicklisp/setup.lisp
; Loading /usr/lib64/LispWorks/lib/7-1-0-0/load-on-demand/utilities/asdf.64ufasl on demand...
Warning: Using DEFPACKAGE to modify #<The QL-SETUP package, 25/32 internal, 3/16 external>.
; Loading /usr/lib64/LispWorks/lib/7-1-0-0/load-on-demand/processes/comm-defsys.lisp on demand...
;; Creating system "COMM"
; Loading /usr/lib64/LispWorks/lib/7-1-0-0/load-on-demand/ccl/describe.64ufasl on demand...
; Loading /usr/lib64/LispWorks/lib/7-1-0-0/load-on-demand/ccl/inspector-values.64ufasl on demand...
; Loading /usr/lib64/LispWorks/lib/7-1-0-0/load-on-demand/ffi/types/inspector.64ufasl on demand...

CL-USER 1 > '(a⍳c)

Error: Cannot read character U+008D as part of a token because it has constituent trait 'invalid'.
  1 (abort) Return to level 0.
  2 Return to top-level loop.
  3 Return from multiprocessing.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

CL-USER 1 : 1 > 1
1

CL-USER 2 : 1 > "a⍳c"
"a⍳c"

CL-USER 3 : 1 > (ql:quickload :maxpc)
To load "maxpc":
  Load 1 ASDF system:
    maxpc
; Loading "maxpc"

(:MAXPC)

CL-USER 4 : 1 > (use-package :maxpc)
T

CL-USER 5 : 1 > (parse "a⍳c" (%some (=element)))
(#\a #\ #\U+008D #\ #\c)
T
T

CL-USER 6 : 1 > 'λ
λ

CL-USER 7 : 1 > (parse "aλc" (%some (=element)))
(#\a #\ #\ #\c)
T
T

CL-USER 8 : 1 > '(aλc)
(AλC)

CL-USER 9 : 1 > (parse '(aλc) (%some (=element)))
(AλC)
T
T

CL-USER 10 : 1 > (parse '(aλc 2 3) (%some (=element)))
(AλC 2 3)
T
T

CL-USER 11 : 1 > 
```

**Comment by eugeneia** [comment]
Actually, thinking about this some more: ANSI CL states that

> (char s j) ≡ (aref (the string s) j)

…but MaxPC gets the character in a `simple-string` via `(aref (the simple-string <s>) <n>)`. This seems to work on all open source implementations but LispWorks is probably within its rights in yielding the byte instead of the character at that position. Note that in order to fix this in MaxPC we need a way to get the byte length of a character’s encoding. Not sure how to do that.
